version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    labels:
      - "🧹 chore"
    reviewers:
      - "alexjustesen"
      - "chrisjm"
    commit-message:
      prefix: "gh actions"
